FROM openjdk:17

WORKDIR /springboot-backend

COPY springboot-backend/out/artifacts/springboot_backend_jar/springboot-backend.jar springboot-backend.jar

CMD ["java", "-jar", "springboot-backend.jar"]
